import { StrictMode } from 'react';

import * as client from 'react-dom/client';

import { RouterProvider, createRouter } from '@tanstack/react-router';

import './index.css';

// Auto-generated by @tanstack/router-vite-plugin when you run `vite dev`
import { routeTree } from './routeTree.gen';

const router = createRouter({ routeTree });

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

client.createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>,
);
