/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as TreasuryIndexRouteImport } from './routes/treasury/index';
import { Route as TreasuryEntryIdRouteImport } from './routes/treasury/$entryId';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const TreasuryIndexRoute = TreasuryIndexRouteImport.update({
  id: '/treasury/',
  path: '/treasury/',
  getParentRoute: () => rootRouteImport,
} as any);
const TreasuryEntryIdRoute = TreasuryEntryIdRouteImport.update({
  id: '/treasury/$entryId',
  path: '/treasury/$entryId',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/treasury/$entryId': typeof TreasuryEntryIdRoute;
  '/treasury/': typeof TreasuryIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/treasury/$entryId': typeof TreasuryEntryIdRoute;
  '/treasury': typeof TreasuryIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/treasury/$entryId': typeof TreasuryEntryIdRoute;
  '/treasury/': typeof TreasuryIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/treasury/$entryId' | '/treasury/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/treasury/$entryId' | '/treasury';
  id: '__root__' | '/' | '/treasury/$entryId' | '/treasury/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  TreasuryEntryIdRoute: typeof TreasuryEntryIdRoute;
  TreasuryIndexRoute: typeof TreasuryIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/treasury/': {
      id: '/treasury/';
      path: '/treasury';
      fullPath: '/treasury/';
      preLoaderRoute: typeof TreasuryIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/treasury/$entryId': {
      id: '/treasury/$entryId';
      path: '/treasury/$entryId';
      fullPath: '/treasury/$entryId';
      preLoaderRoute: typeof TreasuryEntryIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TreasuryEntryIdRoute: TreasuryEntryIdRoute,
  TreasuryIndexRoute: TreasuryIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
