name: Acceptance Stage

on:
  repository_dispatch:
    types: [acceptance-stage]

env:
  IMAGE_TAG: ${{ github.event.client_payload.image_tag }}
concurrency:
  group: acceptance-frontend-staging
  cancel-in-progress: true

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-24.04
    steps:
      - name: Dispatch deploy to staging
        uses: peter-evans/repository-dispatch@v4
        with:
          repository: https://github.com/quangbach27/sumni-finance-deployment
          event-type: deploy-frontend
          client-payload: '{"image_tag": "${{ github.event.client_payload.image_tag }}", "env": "staging"}'